# Generated by Django 5.0.6 on 2024-06-13 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="centresdinteret",
            old_name="couleur",
            new_name="cinema",
        ),
    ]
