# Generated by Django 5.0.6 on 2024-06-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_friendship_privatechat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendship",
            old_name="User1",
            new_name="user1",
        ),
        migrations.RenameField(
            model_name="friendship",
            old_name="User2",
            new_name="user2",
        ),
        migrations.RemoveField(
            model_name="privatechat",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="privatechat",
            name="user2",
        ),
        migrations.AddField(
            model_name="privatechat",
            name="connection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat",
                to="app.connection",
            ),
        ),
    ]
